# Generated by Django 4.2.2 on 2023-08-15 02:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('descripcion', ckeditor.fields.RichTextField(null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='auto/')),
                ('fecha_fabricacion', models.DateField()),
            ],
        ),
    ]
