# Generated by Django 4.2.2 on 2023-08-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='auto'),
        ),
    ]
